platform :ios,'6.0'

pod 'TestFlightSDK', '2.1.3'
pod 'BlocksKit', '2.0.0'
pod 'SDWebImage', '3.5.2'
pod 'SFHFKeychainUtils', '0.0.1'
pod 'InAppSettingsKit', '2.0'
pod 'FlatUIKit', '1.2'
pod 'MBProgressHUD', '0.8'
pod 'SVPullToRefresh', '0.4.1'
pod 'TMCache', '1.2.0'
pod 'MZFormSheetController', '2.2.2'
pod 'GRMustache', '6.8.4'

# development with Pods
#pod 'WZPlayerSlider', :path => '~/arcadia/KWPods/WZPlayerSlider'
pod 'WZAVPlayer', :path => '~/arcadia/KWPods/WZAVPlayer'
pod 'WZGarapon', :path => '~/arcadia/KWPods/WZGarapon'
#pod 'WZActivityIndicatorView', :path => '~/arcadia/KWPods/WZActivityIndicatorView'

pod 'WZPlayerSlider', :git => 'https://github.com/makotokw/CocoaWZPlayerSlider.git'
#pod 'WZAVPlayer', :git => 'https://github.com/makotokw/CocoaWZAVPlayer.git'
#pod 'WZGarapon', :git => 'https://github.com/makotokw/CocoaWZGarapon.git'
pod 'WZActivityIndicatorView', :git => 'https://github.com/makotokw/CocoaWZActivityIndicatorView.git'