platform :ios,'6.0'

pod 'BlocksKit', '1.8.3'
pod 'SDWebImage', '3.7.1'
pod 'SFHFKeychainUtils', '0.0.1'
pod 'InAppSettingsKit', '2.0'
pod 'FlatUIKit', '1.6'
pod 'MBProgressHUD', '0.8'
pod 'SVPullToRefresh', '0.4.1'
pod 'TMCache', '1.2.0'
pod 'MZFormSheetController', '1.3.1'
pod 'GRMustache', '6.8.3'

# development with Pods
#pod 'WZPlayerSlider', :path => '~/arcadia/KWPods/WZPlayerSlider'
#pod 'WZAVPlayer', :path => '~/arcadia/KWPods/WZAVPlayer'
#pod 'WZGarapon', :path => '~/arcadia/KWPods/WZGarapon'
#pod 'WZActivityIndicatorView', :path => '~/arcadia/KWPods/WZActivityIndicatorView'

pod 'WZPlayerSlider', :git => 'https://github.com/makotokw/CocoaWZYPlayerSlider.git', :commit => '2f80881983bb8b1cb8a5f98010bf83f28a9f5863'
pod 'WZAVPlayer', :git => 'https://github.com/makotokw/CocoaWZYAVPlayer.git', :commit => '13323f69c3749c0b33bda835b025ddc292df868b'
pod 'WZGarapon', :git => 'https://github.com/makotokw/CocoaWZYGarapon.git', :commit => 'edb7131df2d7c381b299c71b08b6767b099f83d1'
pod 'WZActivityIndicatorView', :git => 'https://github.com/makotokw/CocoaWZActivityIndicatorView.git', :commit => 'e8e8146365ce90328c9941eb7a7e49faef610b8b'